#person:
#  age: 18
#  boss: false
#  birth: 2013/12/13
#  map: {k1: v1,k2: 12}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: 花花
#    age: 2
#  last-name: zhangsan


#server:
#  port: 8080
#spring:
#  profiles:
#    active: product
#---
#server:
#  port: 8083
#spring:
#  profiles: dev
#---
#---
#server:
#  port: 8084
#spring:
#  profiles: product
#---